# Site settings
title: programming
email:
description: > # this means to ignore newlines until "baseurl:"
  Writings about softwares.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aaronackerman.com" # the base hostname & protocol for your site
twitter_username: _aaronackerman_
github_username: aackerman

# Build settings
markdown: kramdown
