development:
  adapter: postgresql
  database: aackerman
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: aackerman-test
  pool: 5
  timeout: 5000
production:
  adapter: sqlite3
  database: aackerman-production
  pool: 5
  timeout: 5000
